"""Native non-printing roof enforcers; actual supports are generated by the slicer."""

from dataclasses import dataclass
from math import hypot
from typing import Literal

from build123d import Face, GeomType, Location, Part, Solid, Vector

from cargo_grid.accessories import FAMILIES, Accessory, accessory_datums
from cargo_grid.jobs import Design, Job
from cargo_grid.parameters import DEFAULT_HOLE_DIAMETER_MM, Interface, Tile, count, positive
from cargo_grid.stacking import Volume
from cargo_grid.tiles import hole_placements, tile_joins

RoofCoverage = Literal["critical", "full"]
RoofSupportMode = Literal["painted", "auto"]
OBJECT_AUTO_SUPPORT = {"enable_support": "1", "support_type": "normal(auto)"}
CRITICAL_PAD_WIDTH_MM = 3.0
MIN_ENFORCER_HALF_SPAN_MM = 1.0


@dataclass(frozen=True)
class RoofSupportSettings:
    """Intentional PETG-base/PLA-interface contact, not a chemistry guarantee."""

    top_gap: float = 0.0
    interface_layers: int = 2
    interface_spacing: float = 0.0
    nozzle_map: tuple[int, int] | None = None
    coverage: RoofCoverage = "critical"
    foot_expansion: float | None = None
    mode: RoofSupportMode = "painted"

    def __post_init__(self) -> None:
        if self.coverage not in ("critical", "full"):
            raise ValueError("roof coverage must be critical or full")
        if self.mode not in ("painted", "auto"):
            raise ValueError("roof support mode must be painted or auto")
        if self.mode == "auto" and self.coverage != "critical":
            raise ValueError(
                "roof coverage applies to painted roof support; auto support covers whole roofs"
            )
        positive("roof interface gap", self.top_gap, zero=True)
        count("roof interface layers", self.interface_layers)
        positive("roof interface spacing", self.interface_spacing, zero=True)
        if self.top_gap == 0 and (self.interface_layers < 2 or self.interface_spacing != 0):
            raise ValueError(
                "zero-contact roof support requires at least two dense interface layers with spacing 0"
            )
        if self.foot_expansion is not None and self.foot_expansion != -1:
            positive("roof support-foot expansion", self.foot_expansion, zero=True)
        if self.nozzle_map is not None:
            if len(self.nozzle_map) != 2:
                raise ValueError("roof supports need a PETG/PLA two-nozzle mapping")
            for nozzle in self.nozzle_map:
                count("physical nozzle", nozzle)
            if set(self.nozzle_map) != {1, 2}:
                raise ValueError("PETG and PLA must use distinct physical nozzles 1 and 2")

    @property
    def contact_mode(self) -> Literal["zero-contact", "gapped"]:
        return "zero-contact" if self.top_gap == 0 else "gapped"

    @property
    def process_override_keys(self) -> set[str]:
        keys = set(self.native_settings()) - {"filament_map", "filament_map_mode"}
        if self.mode == "auto":
            # Global support stays at the profile's off; objects switch it on individually.
            keys.discard("enable_support")
        if self.contact_mode != "zero-contact":
            keys.discard("support_on_build_plate_only")
        return keys

    def native_settings(self) -> dict[str, str | list[str]]:
        settings: dict[str, str | list[str]] = {
            "enable_support": "1" if self.mode == "painted" else "0",
            # Auto mode leaves the support type to each object.
            **({"support_type": "normal(manual)"} if self.mode == "painted" else {}),
            "support_filament": "1",
            "support_interface_filament": "2",
            "support_on_build_plate_only": "0",
            "support_interface_top_layers": str(self.interface_layers),
            "support_top_z_distance": f"{self.top_gap:g}",
            "support_interface_spacing": f"{self.interface_spacing:g}",
        }
        if self.contact_mode == "zero-contact":
            settings["independent_support_layer_height"] = "0"
            settings["support_object_xy_distance"] = "0.4"
        else:
            settings.update(support_expansion="0", support_object_xy_distance="0.35")
        if self.nozzle_map is not None:
            settings.update(
                filament_map=[str(n) for n in self.nozzle_map],
                filament_map_mode="Manual",
            )
        if self.foot_expansion is not None and self.foot_expansion != -1:
            settings["raft_first_layer_expansion"] = f"{self.foot_expansion:g}"
        return settings


RoofSide = Literal["west", "south", "north", "east"]
# A female tool at this Z angle cuts its pocket into the part from the side named here.
_SIDE_BY_ANGLE = {0: "south", 270: "west", 180: "north", 90: "east"}
_SIDE_ORDER = ("west", "south", "north", "east")


@dataclass(frozen=True)
class FemaleRoof:
    """One retained original female pocket roof and the round openings beneath it."""

    side: RoofSide
    index: int
    center: tuple[float, float]
    faces: tuple[Face, ...]
    hole_radius: float
    occupied_openings: tuple[tuple[float, float], ...]


def _tile_spec(design: Design) -> Tile:
    parameters = dict(design.parameters)
    parameters["interface"] = Interface(**parameters["interface"])
    return Tile(**parameters)


def _design_interface(design: Design) -> Interface | None:
    data = design.parameters.get("interface")
    return Interface(**data) if isinstance(data, dict) else None


def _female_joins(design: Design) -> list[dict]:
    """Female tile-edge joins from the same plans and datums the geometry is built from."""
    interface = _design_interface(design)
    if interface is None:
        return []
    family = design.parameters.get("family")
    if design.mating_datums.get("joins") is not None:
        joins = design.mating_datums["joins"]
    elif family is None:
        joins = tile_joins(_tile_spec(design))
    elif family in FAMILIES:
        fields = {
            key: value
            for key, value in design.parameters.items()
            if key in Accessory.__dataclass_fields__
        }
        fields["interface"] = interface
        # Identity parameters leave out a False completion flag; None would mean automatic.
        fields.setdefault("complete_edge_holes", False)
        joins = accessory_datums(Accessory(**fields))["joins"]
    else:
        joins = []
    return [
        join
        for join in joins
        if join["sex"] == "female" and join.get("interface", "tile-dovetail") == "tile-dovetail"
    ]


def _hole_openings(design: Design) -> tuple[float, list[tuple[float, float]]]:
    parameters = design.parameters
    if "family" not in parameters:
        spec = _tile_spec(design)
        placements = hole_placements(spec)
        radius = spec.hole_diameter / 2 if spec.hole_diameter is not None else 0.0
        return radius, [(h.x, h.y) for h in placements if h.accepted]
    diameter = (
        parameters.get("hole_diameter")
        or parameters.get("edge_hole_diameter")
        or DEFAULT_HOLE_DIAMETER_MM
    )
    return diameter / 2, [(h["x"], h["y"]) for h in design.holes if h["accepted"]]


def female_roofs(design: Design) -> list[FemaleRoof]:
    """Locate the planar ceiling of every retained original female pocket on one design."""
    joins = _female_joins(design)
    if not joins:
        return []
    interface = _design_interface(design)
    ceiling = interface.female_opening_height
    half_wall = 25 * interface.unit_scale
    faces = [
        face
        for face in design.shape.faces()
        if face.geom_type == GeomType.PLANE
        and abs(face.bounding_box().min.Z - ceiling) < 1e-5
        and abs(face.bounding_box().max.Z - ceiling) < 1e-5
        and face.normal_at().Z < -0.99
    ]
    radius, openings = _hole_openings(design)
    by_side: dict[str, list[tuple[dict, float]]] = {}
    for join in joins:
        side = _SIDE_BY_ANGLE.get(round(join["angle"]) % 360)
        if side is None or abs(join["angle"] - round(join["angle"])) > 1e-9:
            raise ValueError(f"{design.name}: unsupported female joint angle {join['angle']}")
        x, y = join["position"][:2]
        by_side.setdefault(side, []).append((join, y if side in ("west", "east") else x))
    roofs = []
    for side in _SIDE_ORDER:
        for index, (join, coordinate) in enumerate(
            sorted(by_side.get(side, []), key=lambda item: item[1]), start=1
        ):
            x, y = join["position"][:2]
            depth = join["depth"]
            across_y = side in ("west", "east")
            sign = 1 if side in ("west", "south") else -1
            group = []
            for face in faces:
                bounds = face.bounding_box()
                if across_y:
                    inward = (bounds.min.X - x, bounds.max.X - x)
                    along = face.center().Y - y
                else:
                    inward = (bounds.min.Y - y, bounds.max.Y - y)
                    along = face.center().X - x
                low, high = sorted(sign * value for value in inward)
                if low >= -1e-5 and high <= depth + 1e-5 and abs(along) <= half_wall:
                    group.append(face)
            if not group:
                raise ValueError(
                    f"{design.name}: expected a planar {side} pocket roof at female join {index}"
                )
            group.sort(key=lambda face: (face.center().Y, face.center().X))
            at_center = any(hypot(hx - x, hy - y) < 1e-6 for hx, hy in openings)
            occupied = tuple(
                (hx, hy)
                for hx, hy in openings
                if radius
                and min(face.distance_to(Vector(hx, hy, ceiling)) for face in group)
                <= radius + 1e-6
            )
            roofs.append(
                FemaleRoof(
                    side,
                    index,
                    (x, y),
                    tuple(group),
                    radius if at_center else 0.0,
                    occupied,
                )
            )
    return roofs


def auto_support_reason(design: Design, settings: RoofSupportSettings) -> str | None:
    """Why an auto-mode roof job switches object-scoped normal Auto support on, if it does."""
    if settings.mode != "auto":
        return None
    if female_roofs(design):
        return "retained original female pocket roof"
    if design.bambu_object_settings == OBJECT_AUTO_SUPPORT:
        return "object-scoped normal Auto support already recommended for this accessory"
    return None


def effective_object_settings(design: Design, settings: RoofSupportSettings | None) -> dict:
    """Per-object Bambu settings written for one design in a roof-support job."""
    if settings is not None and auto_support_reason(design, settings):
        return dict(OBJECT_AUTO_SUPPORT)
    return dict(design.bambu_object_settings)


def validate_roof_job(job: Job, settings: RoofSupportSettings, layer_height: float) -> None:
    allowed = ("part", "layout", "catalogue") if settings.mode == "auto" else ("part", "layout")
    if job.kind not in allowed:
        raise ValueError(
            "roof supports require a part or layout job; catalogues and extras are not supported"
            if settings.mode == "painted"
            else "auto roof support requires a part, layout or catalogue job; extras are not supported"
        )
    found_female = False
    for design in job.designs:
        interface = _design_interface(design)
        if interface is None:
            continue
        if interface.joint_style != "original":
            raise ValueError("roof supports require original roofed joints, not full-height")
        if not _female_joins(design):
            continue
        if (
            settings.top_gap + settings.interface_layers * layer_height
            >= interface.female_opening_height
        ):
            raise ValueError("roof support interface consumes the entire pocket height")
        if layer_height >= interface.body_height - interface.female_opening_height:
            raise ValueError("layer height is too large for the roof enforcer")
        found_female = True
    if not found_female:
        raise ValueError(
            "this job has no retained original female pocket roofs to support; "
            "add a tile with a west or south female edge, a female edge, corner or ramp"
        )


def roof_enforcers(
    design: Design, layer_height: float, coverage: RoofCoverage = "critical"
) -> list[Volume]:
    if coverage not in ("critical", "full"):
        raise ValueError("roof coverage must be critical or full")
    roofs = female_roofs(design)
    if not roofs:
        return []
    interface = _design_interface(design)
    half_span = min(
        max(MIN_ENFORCER_HALF_SPAN_MM, layer_height),
        interface.body_height - interface.female_opening_height,
    )
    volumes = []
    for roof in roofs:
        edge = roof.side
        shapes = [
            Part([Solid.extrude(face, (0, 0, 2 * half_span))]).moved(Location((0, 0, -half_span)))
            for face in roof.faces
        ]
        # A tangent round cut can split one roof into two faces.
        # Keep full masks separate to avoid a nonmanifold shared edge.
        masks = [
            ("full" if len(shapes) == 1 else f"full_{n + 1}", shape)
            for n, shape in enumerate(shapes)
        ]
        if coverage == "critical":
            across_y = edge in ("west", "east")
            center = roof.center[1] if across_y else roof.center[0]
            offset = max(6.0, roof.hole_radius + 1.0)
            bounds = Part([solid for shape in shapes for solid in shape.solids()]).bounding_box()
            masks = []
            for band, low in (
                ("lower", center - offset - CRITICAL_PAD_WIDTH_MM),
                ("upper", center + offset),
            ):
                if across_y:
                    size = (bounds.size.X + 2, CRITICAL_PAD_WIDTH_MM, bounds.size.Z + 2)
                    origin = (bounds.min.X - 1, low, bounds.min.Z - 1)
                else:
                    size = (CRITICAL_PAD_WIDTH_MM, bounds.size.Y + 2, bounds.size.Z + 2)
                    origin = (low, bounds.min.Y - 1, bounds.min.Z - 1)
                clip = Solid.make_box(*size).moved(Location(origin))
                solids = []
                for shape in shapes:
                    clipped = shape.intersect(clip)
                    if clipped is not None:
                        solids.extend(clipped.solids())
                if not solids:
                    raise ValueError(
                        f"{design.name}: critical {edge} roof pad does not fit; select full roof coverage"
                    )
                masks.append((band, Part(solids)))
        for band, mask in masks:
            if not mask.is_valid or len(mask.solids()) != 1 or mask.volume <= 0:
                raise ValueError(f"{design.name}: invalid {edge} roof enforcer")
            volumes.append(
                Volume(
                    f"{design.name}_{edge}_roof_{roof.index}_{coverage}_{band}_enforcer",
                    mask,
                    "roof-enforcer",
                    1,
                    subtype="support_enforcer",
                    roof_side=edge,
                    roof_index=roof.index,
                )
            )
    return volumes
